enabledForges = ["kudubuilderaarch64", "kudubuilderx86"]

[global]
stackName = "aws-infra-forge"
dualStack = true
description = "Cross-Platform Apache Kudu Build Environment: Automates the compilation of Apache Kudu from source code on both x86_64 and ARM64 architectures, enabling native binary generation for heterogeneous deployment scenarios. The solution provisions high-performance compute instances (c6a.16xlarge for x86_64 and c7g.16xlarge for ARM64) with optimized build environments, pre-installed dependencies, and sufficient storage for source code, build artifacts, and compilation intermediates. All build processes run with non-root privileges for enhanced security. The environment supports parallel compilation across multiple CPU cores for accelerated build times, with automatic artifact organization and optional S3 upload capabilities. Ideal for organizations requiring custom Kudu builds with specific optimizations, patches, or features across multiple processor architectures, facilitating true cross-platform deployment and testing of this high-performance columnar storage system."

[forges]
[forges.vpc]
[forges.vpc.defaults]
id = "vpc"
type = "VPC"
cidrBlock = "10.69.0.0/16"
natGatewayPerAZ = false
[forges.ec2]
[forges.ec2.defaults]
type = "EC2"
security = "private"
subnet = "private"
azIndex = 2
debug = false
instanceType = "c7g.xlarge"
instanceCount = 1
keyName = "aws-infra-forge"
detailedMonitoring = false
ebsVolumeType = "gp3"
ebsSize = 30
ebsThroughput = 125
ebsIops = 3000
ebsOptimized = false
enclaveEnabled = false
networkCardCount = 1
purchaseOption = "od"
spotMaxPrice = ""
capacityBlockId = ""
enableEfa = false
enaSrdEnabled = false
osArch = "aarch64"
osName = "amazon"
osType = "linux"
osVersion = "2023"
policies = "AmazonS3FullAccess,AmazonSSMManagedInstanceCore"
s3Location = "s3://aws-infra-forge"
allowedPorts = "22@0.0.0.0/0;80,443,8443@10.69.0.0/16"
allowedPortsIpv6 = "22,80,443,8443@::/0"
requireImdsv2 = true
userDataScriptPath = ""
userDataToken = "sysinfo"

[[forges.ec2.instances]]
id = "kudubuilderx86"
instanceType = "c6a.16xlarge"
osArch = "x86_64"
ebsSize = 300
instanceCount = 1
userDataToken = "kudubuilder-nonroot"

[[forges.ec2.instances]]
id = "kudubuilderaarch64"
instanceType = "c7g.16xlarge"
ebsSize = 300
instanceCount = 1
userDataToken = "kudubuilder-nonroot"
