enabledForges = ["fsx", "eks", "hyperpod"]

[global]
stackName = "aws-infra-forge"
dualStack = true
description = "Advanced HyperPod on EKS Solution: Delivers a production-ready distributed machine learning platform built on EKS with intelligent autoscaling and high-performance networking optimizations. The solution extends the robust EKS foundation with specialized ML/AI capabilities including multi-EFA (Elastic Fabric Adapter) support for ultra-low latency GPU communication and multi-NIC pod networking for distributed training workloads. Features automatic VPC CNI upgrades to enable advanced networking capabilities on compatible instances (g6e, p5, p6, p6e, etc.).  The platform includes comprehensive HPC benchmarking tools with NCCL tests, OSU benchmarks, and EFA-optimized performance testing across multi-architecture support (AMD64/ARM64). Specialized node pools are enhanced for ML workloads with unlimited Karpenter scaling, advanced GPU device plugins, and optimized tolerations for training jobs. Storage integration supports high-performance options including EFS and FSx for Lustre with enhanced I/O testing capabilities (IOR, fio).  The solution automatically provisions cluster admin utilities for streamlined operations and includes a unified HPC performance testing suite with tools like AWS-OFI-NCCL, GDRCopy, and nvbandwidth for GPU memory optimization. Deployment maintains full customization control over EKS versions, Karpenter configurations, and ML-specific components while providing production-grade reliability for large-scale distributed training workloads."

[forges]
[forges.vpc]
[forges.vpc.defaults]
id = "vpc"
type = "VPC"
cidrBlock = "10.69.0.0/16"
natGatewayPerAZ = false
[forges.efs]
[forges.efs.defaults]
security = "isolated"
subnet = "isolated"
type = "EFS"

[[forges.efs.instances]]
id = "efs"
[forges.lustre]
[forges.lustre.defaults]
dataCompressionType = "lz4"
deploymentType = "scratch2"
fileSystemVersion = "2.15"
perUnitStorageThroughput = 250
removalPolicy = "destory"
azIndex = 1
security = "isolated"
storageCapacityGiB = 1200
subnet = "isolated"
type = "LUSTRE"

[[forges.lustre.instances]]
id = "fsx"
[forges.eks]
[forges.eks.defaults]
type = "EKS"
security = "private"
subnet = "private"
instanceTypes = "m6i.xlarge,m6i.2xlarge"
osType = "bottlerocket"
windowsType = "core_2022"
keyName = "aws-infra-forge"
gpuType = "standard"
osArch = "x86_64"
minSize = 2
maxSize = 5
diskSize = 30
eksVersion = "1.33"
adminUsers = ""
controlPlaneAzIndices = "1,2"
commentNvidiaPluginVersion = "=== https://catalog.ngc.nvidia.com/orgs/nvidia/containers/k8s-device-plugin/tags ==="
nvidiaPluginVersion = "0.17.3"
commentNeuronDevicePluginVersion = "=== https://gallery.ecr.aws/neuron/neuron-device-plugin ==="
neuronDevicePluginVersion = "2.27.7.0"
commentEfaPluginVersion = "=== https://artifacthub.io/packages/helm/aws/aws-efa-k8s-device-plugin ==="
efaPluginVersion = "0.5.17"
commentPodIdentityAgentVersion = "=== https://gallery.ecr.aws/eks/eks-pod-identity-agent ==="
podIdentityAgentVersion = "latest"
commentAwsLoadBalancerControllerVersion = "=== https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller ==="
awsLoadBalancerControllerVersion = "1.13.4"
commentCertManagerVersion = "=== https://artifacthub.io/packages/helm/cert-manager/cert-manager ==="
certManagerVersion = "1.18.2"
commentMetricsServerVersion = "=== https://github.com/kubernetes-sigs/metrics-server/releases ==="
metricsServerVersion = "3.13.0"
commentMountpointS3CsiDriverVersion = "=== https://github.com/awslabs/mountpoint-s3-csi-driver/releases ==="
mountpointS3CsiDriverVersion = "2.0.0"
s3BucketName = "aws-infra-forge"
deployCsiDriver = false
createStorageClass = false
storageClassName = "sc"
createStaticPV = false
createDefaultPVC = false
defaultPVCNamespace = "default"
deployTrainingOperator = false
commentTrainingOperatorVersion = "=== https://github.com/kubeflow/trainer/tags ==="
trainingOperatorVersion = "1.9.3"
commentMlflowVersion = "=== https://artifacthub.io/packages/helm/community-charts/mlflow ==="
mlflowVersion = "1.6.2"
enableHyperPodComponents = false
useModernTrainingOperator = false
karpenterVersion = "1.7.1"
karpenterNodePools = "cpu,gpu,neuron"
karpenterOsType = "linux"
commentCpu = "=== 通用 CPU 节点池 ==="
karpenterCpuInstanceFamilies = ""
karpenterCpuInstanceCategories = "c,m,r"
karpenterCpuInstanceGenerations = "5,6,7"
karpenterCpuInstanceTypes = ""
karpenterCpuCapacityTypes = "spot,on-demand"
karpenterCpuArchitectures = "amd64,arm64"
karpenterCpuDiskSize = 100
karpenterCpuLabels = "workload-type=general"
commentGpu = "=== GPU 训练节点池 ==="
karpenterGpuInstanceFamilies = ""
karpenterGpuInstanceCategories = ""
karpenterGpuInstanceGenerations = ""
karpenterGpuInstanceTypes = "g5.xlarge,g5.2xlarge,g4dn.xlarge,g5g.xlarge"
karpenterGpuCapacityTypes = "spot,on-demand"
karpenterGpuArchitectures = "amd64,arm64"
karpenterGpuDiskSize = 200
karpenterGpuTaints = "nvidia.com/gpu=true:NoSchedule"
karpenterGpuLabels = "accelerator=nvidia,workload-type=training"
commentNeuron = "=== Neuron 推理节点池 ==="
karpenterNeuronInstanceFamilies = ""
karpenterNeuronInstanceCategories = ""
karpenterNeuronInstanceGenerations = ""
karpenterNeuronInstanceTypes = "inf1.xlarge,inf2.xlarge"
karpenterNeuronCapacityTypes = "spot,on-demand"
karpenterNeuronArchitectures = "amd64"
karpenterNeuronDiskSize = 150
karpenterNeuronTaints = "aws.amazon.com/neuron=true:NoSchedule"
karpenterNeuronLabels = "accelerator=neuron,workload-type=inference"

[[forges.eks.instances]]
id = "eks"
eksVersion = "1.32"
dependsOn = "LUSTRE:fsx"
deployCsiDriver = true
createStorageClass = true
deployTrainingOperator = true
createStaticPV = true
enableHyperPodComponents = true
createDefaultPVC = true
[forges.hyperpod]
[forges.hyperpod.defaults]
type = "HYPERPOD"
security = "private"
subnet = "private"
clusterName = "hyperpod-eks"
nodeProvisioningMode = "Continuous"
nodeRecovery = "Automatic"
instanceGroupName = "gpu"
instanceType = "ml.g5.xlarge"
instanceCount = 0
azIndex = 1
threadsPerCore = 1
eksVersion = "1.32"
ebsVolumeSizeGb = 500
createLustre = true
lustreStorageCapacity = 1200
lustreThroughput = 250
useDefaultLifecycle = true
enableKarpenterScaling = true
onCreateScript = "on_create.sh"
sourceS3Uri = "s3://aws-infra-forge/lifecycle/"
executionRolePolicies = "AmazonSageMakerFullAccess,AmazonEKSClusterPolicy,AmazonEKSWorkerNodePolicy,AmazonEKS_CNI_Policy,AmazonEC2ContainerRegistryReadOnly,AmazonSSMManagedInstanceCore,AmazonS3FullAccess"

[[forges.hyperpod.instances]]
id = "hyperpod"
dependsOn = "EKS:eks"
